version: '3.7'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    logging:
      options:
        max-size: 10m
        max-file: "3"

  webserver:
    image: puckel/docker-airflow:skooldio
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=y
      - EXECUTOR=Local
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgres://airflow:airflow@postgres:5432/airflow
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./dags:/usr/local/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
      - ./fileinput:/usr/local/airflow/fileinput
      - ./plugins:/usr/local/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  telegraf:
    container_name: telegraf
    image: telegraf:1.12.3
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf

  influxdb:
    container_name: influxdb
    image: influxdb:1.7.8
    ports:
      - "8083:8083"
      - "8086:8086"
    # Uncomment this section to keep data
    #volumes:
    #- ./mnt/influxdb:/var/lib/influxdb

  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "3000:3000"
